# Generated by Django 3.2 on 2022-01-22 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_cart_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart_table',
            old_name='fodid',
            new_name='foodid',
        ),
    ]
