# Generated by Django 3.2 on 2022-01-24 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_donation_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='ngo_login',
            name='Dnno',
            field=models.IntegerField(default=0),
        ),
    ]
