# Generated by Django 3.2 on 2022-01-24 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_ngo_login_dnno'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orid', models.CharField(max_length=200)),
                ('resid', models.CharField(max_length=200)),
                ('dnrid', models.CharField(max_length=200)),
                ('fname', models.CharField(max_length=200)),
                ('fqty', models.CharField(max_length=200)),
                ('donation_date', models.DateField(auto_now=True)),
                ('accept_date', models.CharField(default='nil', max_length=200)),
                ('status', models.CharField(default='not_accepted', max_length=200)),
            ],
        ),
    ]
