# Generated by Django 3.2 on 2022-12-17 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_request_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Donor_login',
            new_name='Usertable',
        ),
        migrations.DeleteModel(
            name='Cart_table',
        ),
        migrations.DeleteModel(
            name='Donation_table',
        ),
        migrations.DeleteModel(
            name='NGO_login',
        ),
        migrations.DeleteModel(
            name='Request_table',
        ),
        migrations.DeleteModel(
            name='Resto_login',
        ),
        migrations.DeleteModel(
            name='Stock_table',
        ),
    ]
